---
- name: update files
  hosts: master
  become: yes

  tasks:
    - name: copy file
      copy:
        src: ./
        dest: ~/
    
    - name: docker build
      shell: docker build -t dltoa6746/PersonalProject:blue ~/

    - name: docker push
      shell: docker push dltoa6746/PersonalProject:blue

    - name: kubernetes create
      shell: kubectl apply -f ~/nginx.yaml
