---
- name: update files
  hosts: vm
  become: yes

  tasks: 
    - name: copy file 
      copy: 
      src: ./
      dest: ~/jenkins/

    - name: docker build
      shell: docker build -t dltoa6746/PersomalProject:1.0 ~/jenkins/

    - name: docker push 
      shell: docker push dltoa6746/PersonalProject:1.0

    - name: kubernetes create 
      shell: kubectl apply -f ~/jenkins/deploysvc.yaml
