---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:             #<-- 여기서부터는 포드에 대한 내용
    metadata:
      name: nginx-pod
      labels:
        app: nginx
    spec:               #<-- 컨테이너에 대한 내용
      containers:
      - name: nginx-ctn
        image: dltoa6746/personalproject:blue
        ports:
        - containerPort: 80
