---
- name: update files
  hosts: master
  become: yes

  tasks:
    - name: copy file
      copy:
        src: ./
        dest: ~/jenkins/
    
    - name: docker build
      shell: docker build -t dltoa6746/PersonalProject:1.0 ~/jenkins/

    - name: docker push
      shell: docker push dltoa6746/PersonalProject:1.0

    - name: kubernetes create
      shell: kubectl apply -f ~/jenkins/nginx.yaml
